# Generated by Django 5.2.17 on 2026-09-22 04:47

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sap_success_factors_channel",
            "0006_sapsuccessfactorsenterprisecustomerconfiguration_transmit_course_hours",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="auth_type",
            field=models.CharField(
                choices=[
                    (
                        "sap_signed_assertion",
                        "SAP-signed SAML assertion (SAP IdP API + client secret)",
                    ),
                    (
                        "self_signed_assertion",
                        "Self-signed SAML assertion (our private key)",
                    ),
                ],
                default="sap_signed_assertion",
                help_text="How access tokens are obtained for this customer. 'SAP-signed' asks SAP's OAuth IdP API to mint the SAML assertion for us, authenticated with the OAuth client id/secret below; 'Self-signed' means we sign the assertion ourselves with the configured private key instead. Existing customers stay on 'SAP-signed' until they have been migrated. Self-signed support is still under development and is not yet used to authenticate any transmissions.",
                max_length=32,
                verbose_name="SAP Auth Type",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="decrypted_private_key",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="The PEM-encoded private key used to sign the SAML bearer assertion sent to this customer's token endpoint. Only used for a self-signed SAML assertion. It will be encrypted when stored in the database.",
                null=True,
                verbose_name="Encrypted Private Key",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="decrypted_private_key_passphrase",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Passphrase protecting the private key above, if any. Leave blank if the private key is not passphrase-protected. Only used for a self-signed SAML assertion. It will be encrypted when stored in the database.",
                max_length=255,
                null=True,
                verbose_name="Encrypted Private Key Passphrase",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsenterprisecustomerconfiguration",
            name="saml_assertion_audience",
            field=models.CharField(
                blank=True,
                default="www.successfactors.com",
                help_text="Value of the Audience restriction in the SAML bearer assertion sent to this customer's token endpoint. Only used for a self-signed SAML assertion.",
                max_length=255,
                verbose_name="SAML Assertion Audience",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsglobalconfiguration",
            name="oauth_token_api_path",
            field=models.CharField(
                blank=True,
                default="/oauth/token",
                help_text="Path, relative to a customer's SAP base URL, of the endpoint that exchanges a SAML bearer assertion for an access token.",
                max_length=255,
                verbose_name="OAuth Token API Path",
            ),
        ),
        migrations.AddField(
            model_name="sapsuccessfactorsglobalconfiguration",
            name="saml_assertion_api_path",
            field=models.CharField(
                blank=True,
                default="/oauth/idp",
                help_text="Path, relative to a customer's SAP base URL, of the endpoint that issues the SAML assertion exchanged for an access token.",
                max_length=255,
                verbose_name="SAML Assertion API Path",
            ),
        ),
    ]
